# Generated by Django 4.2.30 on 2026-05-09 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('api_url', models.URLField(verbose_name='API URL (например, http://ip:port)')),
                ('username', models.CharField(max_length=100, verbose_name='Логин панели')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль панели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('remark_prefix', models.CharField(default='VPN', max_length=50, verbose_name='Префикс для ремарки')),
            ],
            options={
                'verbose_name': 'Нода',
                'verbose_name_plural': 'Ноды',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен подписки')),
                ('name', models.CharField(default='Основная подписка', max_length=100, verbose_name='Название подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('data_limit', models.BigIntegerField(default=0, verbose_name='Лимит трафика (байт)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_id', models.IntegerField(verbose_name='ID инбаунда в 3x-ui')),
                ('remark', models.CharField(max_length=100, verbose_name='Название/Ремарка')),
                ('protocol', models.CharField(default='vless', max_length=20, verbose_name='Протокол')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес подключения (IP/Домен)')),
                ('sni', models.CharField(blank=True, max_length=255, verbose_name='SNI')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Host')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Path')),
                ('security', models.CharField(default='tls', max_length=20, verbose_name='Security')),
                ('network', models.CharField(default='ws', max_length=20, verbose_name='Network')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='vpn_app.node', verbose_name='Нода')),
            ],
            options={
                'verbose_name': 'Инбаунд',
                'verbose_name_plural': 'Инбаунды',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, verbose_name='XRAY UUID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (в панели)')),
                ('up', models.BigIntegerField(default=0, verbose_name='Отправлено')),
                ('down', models.BigIntegerField(default=0, verbose_name='Получено')),
                ('total_used', models.BigIntegerField(default=0, verbose_name='Всего использовано')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включен в панели')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='vpn_app.inbound', verbose_name='Инбаунд')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='vpn_app.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'unique_together': {('subscription', 'inbound')},
            },
        ),
    ]
