# Generated by Django 4.2.30 on 2026-05-09 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Multi-Node Sub', max_length=100, verbose_name='Название')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ваш токен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сводная подписка',
                'verbose_name_plural': 'Сводные подписки',
            },
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на подписку (от 3x-ui)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='vpn_app.aggregatesubscription')),
            ],
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='node',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Inbound',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
