# Generated by Django 4.2.30 on 2026-05-09 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_app', '0002_aggregatesubscription_sourcelink_remove_inbound_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatesubscription',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='Токен подписки'),
        ),
    ]
