# Generated by Django 4.2.30 on 2026-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_app', '0003_alter_aggregatesubscription_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelink',
            name='config_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во конфигов'),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка'),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='last_status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код ответа'),
        ),
    ]
