# Generated by Django 4.2.30 on 2026-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_app', '0004_sourcelink_config_count_sourcelink_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelink',
            name='remark',
            field=models.CharField(blank=True, help_text='Напр.: Сервер Германия', max_length=255, verbose_name='Примечание'),
        ),
    ]
