# Generated by Django 4.2.30 on 2026-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_app', '0005_sourcelink_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatesubscription',
            name='custom_base_url',
            field=models.CharField(blank=True, help_text='Напр.: subses.doppelgangeres.com:5090', max_length=255, verbose_name='Кастомный домен/URL'),
        ),
    ]
