# Generated by Django 4.2.30 on 2026-05-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_app', '0006_aggregatesubscription_custom_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatesubscription',
            name='client_title',
            field=models.CharField(blank=True, help_text='То, что увидит пользователь в приложении', max_length=100, verbose_name='Название (для клиента)'),
        ),
        migrations.AlterField(
            model_name='aggregatesubscription',
            name='name',
            field=models.CharField(default='My Multi-Node Sub', max_length=100, verbose_name='Название (внутреннее)'),
        ),
    ]
